version: "3"
services:
    zoo1:
        image: zookeeper:3.4.9
        hostname: zoo1
        ports:
          - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zoo1:2888:3888
        volumes:
          - ./zk-single-kafka-single/zoo1/data:/data
          - ./zk-single-kafka-single/zoo1/datalog:/datalog
    
    kafka1:
        image: confluentinc/cp-kafka:5.4.0
        hostname: kafka1
        ports:
          - "9092:9092"
        environment:
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
          KAFKA_LISTENERS: INSIDE://:9092
          KAFKA_ADVERTISED_LISTENERS: INSIDE://${DOCKER_KAFKA_HOST}:9092
          KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
          KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
          KAFKA_BROKER_ID: 1
          KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
          - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
        depends_on:
          - zoo1

    kafka-producer:
        image: ccfd-kafka-producer:latest
        environment: 
            BROKER_URL: 'kafka1:9092'
            KAFKA_TOPIC: 'ccd'

    grafana:
        image: grafana/grafana
        hostname: grafana
        volumes:
          - ./ccfd-demo/deployment/grafana:/etc/grafana/provisioning
        ports:
          - "3000:3000"

    prometheus:
        image: prom/prometheus
        hostname: prometheus
        volumes:
          - ./ccfd-demo/deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
          - "9090:9090"
        # depends_on: 
        #   - kieserver

    seldon:
        image: ruivieira/ccfd-seldon-model:latest
        hostname: seldon
        ports:
            - "5000:5000"

    nexus:
        image: sonatype/nexus
        hostname: nexus
        ports:
            - "8081:8081"

    kiestorage:
      image: postgres
      hostname: kiestorage
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: admin123
        POSTGRES_USER: admin
        POSTGRES_DB: jbpm
        
    kieserver:
        image: ruivieira/ccd-service:1.0-SNAPSHOT
        hostname: kieserver
        ports:
          - "8090:8090"
        environment: 
          SELDON_URL: 'http://seldon:5000'
          BROKER_URL: 'http://kafka1:9092'
          NEXUS_URL: 'http://nexus:8081'
          CUSTOMER_NOTIFICATION_TOPIC: 'ccd-customer-outgoing'
          PG_USERNAME: 'admin'
          PG_PASSWORD: 'admin123'
          DB_HOST: 'kiestorage'
          JAVA_OPTS: '-Dorg.jbpm.task.prediction.service=SeldonPredictionService'

    camel:
        image: ruivieira/ccd-fuse:1.0-SNAPSHOT
        hostname: camel
        environment:
          KIE_SERVER_URL: 'http://kieserver:8090'
          BROKER_URL: 'http://kafka1:9092'
          KAFKA_TOPIC: 'ccd'
          CUSTOMER_NOTIFICATION_TOPIC: 'ccd-customer-outgoing'
          CUSTOMER_RESPONSE_TOPIC: 'ccd-customer-response'
          SELDON_URL: 'http://seldon:5000'

    notifications:
        image: ruivieira/ccfd-notification-service:latest
        hostname: notifications
        environment: 
          BROKER_URL: 'http://kafka1:9092'